//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masny.Food.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Masny.Food.Common.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password is invalid..
        /// </summary>
        public static string AccountLoginError {
            get {
                return ResourceManager.GetString("AccountLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred migrating the DB..
        /// </summary>
        public static string DatabaseMigrateError {
            get {
                return ResourceManager.GetString("DatabaseMigrateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is successfully migrated..
        /// </summary>
        public static string DatabaseMigrateSuccessful {
            get {
                return ResourceManager.GetString("DatabaseMigrateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400 Bad Request.
        /// </summary>
        public static string Error400Description {
            get {
                return ResourceManager.GetString("Error400Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server cannot or will not process the request due to an apparent client error..
        /// </summary>
        public static string Error400Message {
            get {
                return ResourceManager.GetString("Error400Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Page not found.
        /// </summary>
        public static string Error404Description {
            get {
                return ResourceManager.GetString("Error404Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource could not be found but may be available in the future..
        /// </summary>
        public static string Error404Message {
            get {
                return ResourceManager.GetString("Error404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Internal Server Error.
        /// </summary>
        public static string Error500Description {
            get {
                return ResourceManager.GetString("Error500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong..
        /// </summary>
        public static string Error500Message {
            get {
                return ResourceManager.GetString("Error500Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host terminated unexpectedly!.
        /// </summary>
        public static string HostFatalError {
            get {
                return ResourceManager.GetString("HostFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting web host...
        /// </summary>
        public static string HostStart {
            get {
                return ResourceManager.GetString("HostStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
    }
}
